### ISSUE TITLE
Using older version of `django-template-partials`

### ISSUE THREAD

**Issue by jonathan-s** [EmilStenstrom/django-components#1455]
If you happen to be using a somewhat older version (~0.24.0) of `django-template-partials` you get the following scary looking traceback. 

```
  File "/app/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/django_components/util/django_monkeypatch.py", line 260, in _include_render
    return orig_include_render(self, context, *args, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/django_components/util/django_monkeypatch.py", line 352, in _template_proxy_render
    return Template.render(self, context)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/django_components/util/django_monkeypatch.py", line 183, in _template_render
    result = self._render(context, *args, **kwargs)
             ^^^^^^^^^^^^
AttributeError: 'TemplateProxy' object has no attribute '_render'. Did you mean: 'render'?
```

It would be pretty easy to throw a helpful ImportError if the version is lower than the version you have pinned, explaining that you need at least 0.25.2 of the library. That would shave off a somewhat rough edge :). 

Cheers

**Comment by JuroOravec** [comment]
Thanks for bringing this up! I think we can add the missing `_render` method to the `TemplateProxy`, since we're already modifying it in [`monkeypatch_template_proxy_render`](https://github.com/django-components/django-components/blob/a5ebb590597dfc30893f3624faacb5463cc60f20/src/django_components/util/django_monkeypatch.py#L354). That could make django-components compatible also with older versions of `django-template-partials`

```py
if not hasattr(template_proxy_cls, "_render"):
    def _render(self, context):
        return self.nodelist.render(context)

    template_proxy_cls._render = _render
```

**Comment by JuroOravec** [comment]
Just published this as [v0.142.3](https://github.com/django-components/django-components/releases/tag/0.142.3) 🚀  

django-componens now works with django-template-partials v23.3 and later. There's now a section that keeps track of compatibility with other packages

<img width="605" height="337" alt="Image" src="https://github.com/user-attachments/assets/63708afc-665c-4f04-9329-308fa11c17b6" />

**Comment by jonathan-s** [comment]
Excellent!
