### ISSUE TITLE
Error 'Unset' object has no attribute '_render' in multi-threaded environments

### ISSUE THREAD

**Issue by oliverhaas** [EmilStenstrom/django-components#1587]
We were getting the above error in our production environment with django-components 0.147.

I think in `_load_media()`, `resolved_template=True` is set before the base class early-return, leaving `_template` as `UNSET` while marked resolved. Thread 2 could `read _template` while Thread 1 was still loading.

I think this might have been introduced in #1547, but I'm just guessing since it's just the larger recent change in that area.

I'll open a PR in a second to illustrate what I mean. Not sure if my thinking and understanding is fully correct, but I'm fairly certain it's a race condition one way or another.
